name: PR Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: rhysd/action-setup-vim
          with:
            neovim: true
            version: nightly
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            profile: minimal
            override: true
        - name: Install dependencies
          run: |
            git clone --depth 1 https://github.com/nvim-lua/plenary.nvim \
              "$HOME/.local/share/nvim/site/pack/test/start/plenary.nvim"
            cargo install --locked vimcats --features=cli
        - name: Check docs
          run: |
            vimcats -fact $(tr '\n' ' ' < doclist) > /tmp/doc.txt
            diff -u doc/swapdiff.nvim.txt /tmp/doc.txt
        - name: Run tests
          run: bash ./test.sh
